config/routes.rb
Rails.application.routes.draw do
  devise_for :org_people,
             controllers: {
               passwords: 'org_people/passwords',
               sessions: 'org_people/sessions',
               confirmations: 'org_people/confirmations',
               registrations: 'org_people/registrations'
             }
  devise_scope :org_person do
    get 'signup',  to: 'devise/registrations#new'
    get 'signin',  to: 'devise/sessions#new'
    delete 'signout', to: 'devise/sessions#destroy'
  end
  root to: 'catalogues#index'

  resources :catalogues
  resources :org_people

end

app/controllers/org_people/confirmations_controller.rb
class OrgPeople::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  # protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    new_org_person_confirmation_path
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    signin_path
  end
end

app/controllers/org_people/omniauth_callbacks_controller.rb
class OrgPeople::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/org_people/passwords_controller.rb
class OrgPeople::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  # protected

  def after_resetting_password_path_for(resource)
    root_path
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    signin_path
  end
end

app/controllers/org_people/registrations_controller.rb
class OrgPeople::RegistrationsController < Devise::RegistrationsController
before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

# GET /resource/sign_up
def new
  super
end

# POST /resource
def create
  super
end

# GET /resource/edit
def edit
  super
end

  # PUT /resource
def update
  super
end

# DELETE /resource
def destroy
  super
end

# GET /resource/cancel
# Forces the session data which is usually expired after sign
# in to be expired now. This is useful if the user wants to
# cancel oauth signing in/up in the middle of the process,
# removing all OAuth session data.
def cancel
  super
end

  # protected

# If you have extra params to permit, append them to the sanitizer.
def configure_sign_up_params
  devise_parameter_sanitizer.permit(
    :sign_up,
    keys: %i[first_name last_name email password password_confirmation]
  )
end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/org_people/sessions_controller.rb
class OrgPeople::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/org_people/unlocks_controller.rb
class OrgPeople::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/org_people_controller.rb
class OrgPeopleController < ApplicationController
end

app/helpers/org_people_helper.rb
module OrgPeopleHelper
end

app/views/org_people/shared/_links.html.erb
<!-- For  logging in a user and creating the session for them-->
<% if controller_name != 'sessions' %>
  <%= link_to "Log in", new_org_person_session_path %><br />
<% end %>
<!-- For signing up a user with the application -->
<% if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_org_person_registration_path %><br />
<% end %>
<!-- For recovering forgotten passwords  -->
<% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>
<!-- For confirming email addresses -->
<% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_org_person_confirmation_path %><br />
<% end %>

<% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<% if devise_mapping.omniauthable? %>
  <% resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>